[package]
name = "winelist-generator"
version = "0.0.1"
edition = "2021"
description = "Auto generates HTML winelist from cellartracker-data"

[dependencies]
csv = "1.3.0"
reqwest = "0.12.8"
rocket = "0.5.1"

[[bin]]
name = "winelistgen"
path = "src/main.rs"
